spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: users-status-check
              uri: lb://users-service
              predicates:
                - Path=/users/status/check
                - Method=GET
              filters:
                - RemoveRequestHeader=Cookie
            - id: accounts-status-check
              uri: lb://accounts-service
              predicates:
                - Path=/accounts/status/check
                - Method=GET
              #                Sets dates when this route should be available. For example for deployment
              #                - After=2025-07-15T08:15:00+02:00
              #                - Before=2025-07-15T08:15:00+02:00
              #                - Between=2025-07-15T08:00:00+02:00,2025-07-15T08:12:00+02:00
              filters:
                - RemoveRequestHeader=Cookie
    #                Manually set internal path for request. Predicate should be updated as well to match expected path.
    #                - RewritePath=/accounts-service/(?<segment>.*), /${segment}

gateway:
  access:
    time-window:
      enabled: false
      start: 2025-07-15T08:00:00+02:00
      end: 2025-07-15T08:18:00+02:00

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
